#TODO: Add qiime2 prefix to all qiime 2 rules, add proper {input} and {output} to each shell command, revise or
# delete rules that aren't currently being used.

import pandas as pd
configfile: "config/config.yaml"
target = "artifacts/taxa-barplot.qzv", "artifacts/physeq.RDS", "visual_outputs/alpha_div.pdf", "visual_outputs/beta_div.pdf", "visual_outputs/relative_barplot.pdf"
rule all:
    input:
        target
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ BEGINNING OF QIIME2 ANALYSIS SECTION ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rule qiime2_import: 
    input:
        config["manifest"]
    output:
        "artifacts/demux-paired-end.qza"
    params:
        config["data_format"]
    conda:
        "envs/qiime2.yml"
    shell:
        "qiime tools import "
        "--type 'SampleData[PairedEndSequencesWithQuality]' "
        "--input-path {input} "
        "--output-path {output} "
        "--input-format 'PairedEndFastqManifestPhred33V2'"

rule qiime2_demux_summarize:
    input: 
        "artifacts/demux-paired-end.qza"
    output:
        "artifacts/demux-paired-end.qzv"
    conda:
        "envs/qiime2.yml"
    shell:
        "qiime demux summarize "
        "--i-data {input} "
        "--o-visualization {output}"

rule qiime2_trim_paired:
    input:
        "artifacts/demux-paired-end.qza",
    params:
        adapter_f = [f'--p-adapter-f {seq} ' for seq in config["cutadapt"]["adapter_f"].split(',') if seq],
        adapter_r = [f'--p-adapter-r {seq} ' for seq in config["cutadapt"]["adapter_r"].split(',') if seq],
        min_length = config["cutadapt"]["minimum_length"]
    threads:
        config['threads']['trimming']
    output:
        trim_qza = "artifacts/trimmed-seqs.qza",
    conda:
        "envs/qiime2.yml"
    log:
        ".snakemake/log/trim_paired_summarize.log"
    shell:
        "qiime cutadapt trim-paired "
        "--i-demultiplexed-sequences {input} "
        "{params.adapter_f}"
        "{params.adapter_r}"
        "--p-minimum-length {params.min_length} "
        "--p-cores {threads} "
        "--o-trimmed-sequences {output.trim_qza} "
        "--verbose 2> {log} 1>&2"

rule qiime2_denoise_paired: #return code -9 = needs more threads
    input:
        "artifacts/trimmed-seqs.qza"
    params:
        trunclenf = config["trunclenf"],
        trunclenr = config["trunclenr"],
        trimleftf = config["trimleftf"],
        trimleftr = config["trimleftr"]
    threads:
        config['threads']['denoising']
    output:
        rep_seqs = "artifacts/demux-paired-end-rep-seqs.qza",
        table = "artifacts/table.qza",
        denoise_stats = "artifacts/denoising-stats.qza",
        transition_stats = "artifacts/base-transition-stats.qza"
    conda:
        "envs/qiime2.yml"
    shell:
        "qiime dada2 denoise-paired "
        "--i-demultiplexed-seqs {input} "
        "--p-trunc-len-f {params.trunclenf} "
        "--p-trunc-len-r {params.trunclenr} "
        "--p-trim-left-f {params.trimleftf} "
        "--p-trim-left-r {params.trimleftr} "
        "--p-n-threads {threads} "
        "--o-table {output.table} "
        "--o-representative-sequences {output.rep_seqs} "
        "--o-denoising-stats {output.denoise_stats} "
        "--o-base-transition-stats {output.transition_stats}"

"""
rule automated_trim: #CHECKED; need to make sure that all reads are trimmed to same length
    input:
        "artifacts/demux-paired-end-rep-seqs.qza"
    params:
        lowQuality = config["min-quality"],
        qualityWindow = config["quality-window"],
        lengthFraction = config["min-length-fraction"],
        ambiguous = config["max-ambiguous"]
    output:
        "artifacts/rep-seqs.qza"
    conda:
        "envs/qiime2-2022.11-py38-linux-conda.yml"
    shell:
        "qiime quality-filter q-score "
        "--i-demux {input} "
        "--p-min-quality {params.lowQuality} "
        "--p-quality-window {params.qualityWindow} "
        "--p-min-length-fraction {params.lengthFraction} "
        "--p-max-ambiguous {params.ambiguous} "
        "--o-filtered-sequences artifacts/rep-seqs.qza "
        "--o-filter-stats trim_stats.qza"
"""

# (DADA2 return code -9) is a memory issue; run with more cores
rule qiime2_metadata_tabulate:
    input:
        sequences = "artifacts/demux-paired-end-rep-seqs.qza",
        taxonomy = "artifacts/taxonomy.qza",
        table = "artifacts/table-filtered.qza" # must be a .tsv NOT a .csv
    output:
        "artifacts/metadata_tabulated.qzv"
    conda:
        "envs/qiime2.yml"
    shell:
        "qiime metadata tabulate "
        "--m-input-file {input.sequences} "
        "--m-input-file {input.taxonomy} "
        "--m-input-file {input.table} "
        "--o-visualization {output}"

rule export_metadata:
    input:
        "artifacts/metadata_tabulated.qzv"
    output:
        "qiime_output/metadata_summary/"
    conda:
        "envs/qiime2.yml"
    shell:
        "qiime tools export "
        "--input-path artifacts/metadata_tabulated.qzv "
        "--output-path qiime_output/metadata_summary/"

rule classify_sklearn:
    input:
        "artifacts/demux-paired-end-rep-seqs.qza",
        classifier = config["classifier"] #keyword arguments MUST be after positional arguments
    output:
        "artifacts/taxonomy.qza"
    conda:
        "envs/qiime2.yml"
    threads:
        config['threads']['classify_sklearn']
    shell:
        "qiime feature-classifier classify-sklearn "
        "--i-classifier {input.classifier} "
        "--i-reads artifacts/demux-paired-end-rep-seqs.qza "
        "--p-n-jobs {threads} "
        "--o-classification artifacts/taxonomy.qza"

#future automated sample filtering
""" 
qiime feature-table filter-samples \
  --i-table table.qza \
  --p-min-frequency 1500 \
  --o-filtered-table sample-frequency-filtered-table.qza
"""

rule filter_table_frequency:
    input:
        "artifacts/table.qza"
    params:
        table_frequency = config["table-frequency"],
        sample_frequency = config["sample-frequency"]
    output:
        "artifacts/feature-frequency-filtered-table.qza"
    conda:
        "envs/qiime2.yml"
    shell:
        "qiime feature-table filter-features "
        "--i-table artifacts/table.qza "
        "--p-min-frequency {params.table_frequency} "
        "--p-min-samples {params.sample_frequency} "
        "--o-filtered-table artifacts/feature-frequency-filtered-table.qza"

rule filter_table_feature:
    input: 
        "artifacts/feature-frequency-filtered-table.qza",
        "artifacts/taxonomy.qza"
    params:
        included = config["table-include"],
        excluded = config["table-filter"]
    output: 
        "artifacts/table-filtered.qza"
    conda:
        "envs/qiime2.yml"
    shell: 
        "qiime taxa filter-table "
        "--i-table artifacts/feature-frequency-filtered-table.qza " 
        "--i-taxonomy artifacts/taxonomy.qza "
        "--p-include {params.included} "
        "--p-exclude {params.excluded} "
        "--o-filtered-table artifacts/table-filtered.qza"

rule feature_table_summarize:
    input:
        table = "artifacts/table-filtered.qza",
        metadata = config["metadata"]
    output:
        summary = "artifacts/table-filtered.qzv",
        feature_freq = "artifacts/feature-frequencies.qza",
        sample_freq = "artifacts/sample-frequencies.qza"
    conda:
        "envs/qiime2.yml"
    shell:
        "qiime feature-table summarize "
        "--i-table {input.table} "
        "--m-metadata-file {input.metadata} "
        "--o-feature-frequencies {output.feature_freq} "
        "--o-sample-frequencies {output.sample_freq} "
        "--o-summary {output.summary}"


rule rarefy_table:
    input:
        "artifacts/table-filtered.qza"
    output:
        "artifacts/rarefied-table-filtered.qza"
    params:
        sampling_depth = config["sampling_depth_phylogenetic"]
    conda:
        "envs/qiime2.yml"
    shell:
        "qiime feature-table rarefy "
        "--i-table artifacts/table-filtered.qza "
        "--p-sampling-depth {params.sampling_depth} "
        "--o-rarefied-table artifacts/rarefied-table-filtered.qza"

rule tabulate_seqs:
    input:
        "artifacts/demux-paired-end-rep-seqs.qza"
    output:
        "artifacts/demux-paired-end-rep-seqs.qzv"
    conda:
        "envs/qiime2.yml"
    shell:
        "qiime feature-table tabulate-seqs "
        "--i-data {input} "
        "--o-visualization {output}"

rule mafft_fasttree:
    input:
        "artifacts/demux-paired-end-rep-seqs.qza"
    output:
        "artifacts/aligned-rep-seqs.qza",
        "artifacts/masked-aligned-rep-seqs.qza",
        "artifacts/unrooted-tree.qza",
        "artifacts/rooted-tree.qza"
    threads:
        config['threads']['mafft_fasttree']
    conda:
        "envs/qiime2.yml"
    shell:
        "qiime phylogeny align-to-tree-mafft-fasttree "
        "--i-sequences {input} "
        "--p-n-threads {threads} "
        "--o-alignment artifacts/aligned-rep-seqs.qza "
        "--o-masked-alignment artifacts/masked-aligned-rep-seqs.qza "
        "--o-tree artifacts/unrooted-tree.qza "
        "--o-rooted-tree artifacts/rooted-tree.qza"

rule plot_rarefaction_curve:
    input:
        table = "artifacts/table-filtered.qza",
        tree = "artifacts/rooted-tree.qza",
        metadata = config["metadata"]
    output:
        "artifacts/alpha-rarefaction.qzv"
    params:
        sampling_depth = config["sampling_depth_phylogenetic"]
    conda:
        "envs/qiime2.yml"
    shell:
        "qiime diversity alpha-rarefaction "
        "--i-table {input.table} "
        "--i-phylogeny {input.tree} "
        "--p-max-depth {params.sampling_depth} "
        "--m-metadata-file {input.metadata} "
        "--o-visualization {output}"

rule taxonomy_tabulate:
    input:
        "artifacts/taxonomy.qza"
    output:
        "qiime_output/taxonomy.qzv"
    conda:
        "envs/qiime2.yml"
    shell:
        "qiime metadata tabulate "
        "--m-input-file artifacts/taxonomy.qza "
        "--o-visualization qiime_output/taxonomy.qzv"

rule core_metrics_phylogenetic:
    input:
        "artifacts/rooted-tree.qza",
        "artifacts/rarefied-table-filtered.qza",
        metadata = config["metadata"]
    output:
        "core-metrics-results/bray_curtis_distance_matrix.qza",
        temp("core-metrics-results/unweighted_unifrac_distance_matrix.qza"),
        temp("core-metrics-results/evenness_vector.qza"),
        temp("core-metrics-results/faith_pd_vector.qza"),
        temp("core-metrics-results/table-filtered.qza"),
        temp("core-metrics-results/observed-otus-vector.qza"),
        "core-metrics-results/shannon-vector.qza",
        temp("core-metrics-results/jaccard-distance-matrix.qza"),
        temp("core-metrics-results/jaccard-pcoa-results.qza"),
        temp("core-metrics-results/bray-curtis-pcoa-results.qza"),
        temp("core-metrics-results/jaccard-emperor.qzv"),
        "core-metrics-results/bray-curtis-emperor.qzv",
        temp("core-metrics-results/weighted-unifrac-distace-matrix.qza"),
        "core-metrics-results/unweighted-unifrac-pcoa-results.qza",
        temp("core-metrics-results/weighted-unifrac-pcoa-results.qza"),
        "core-metrics-results/unweighted-unifrac-emperor.qzv",
        temp("core-metrics-results/weighted-unifrac-emperor.qzv")
    params:
        config = config["sampling_depth_phylogenetic"]
    conda:
        "envs/qiime2.yml"
    shell:
        "qiime diversity core-metrics-phylogenetic "
        "--i-phylogeny artifacts/rooted-tree.qza "
        "--i-table artifacts/rarefied-table-filtered.qza "
        "--p-sampling-depth {params.config} " 
        "--m-metadata-file {input.metadata} "
        "--o-bray-curtis-distance-matrix core-metrics-results/bray_curtis_distance_matrix.qza "
        "--o-unweighted-unifrac-distance-matrix core-metrics-results/unweighted_unifrac_distance_matrix.qza "
        "--o-evenness-vector core-metrics-results/evenness_vector.qza "
        "--o-faith-pd-vector core-metrics-results/faith_pd_vector.qza "
        "--o-rarefied-table core-metrics-results/table-filtered.qza "
        "--o-observed-features-vector core-metrics-results/observed-otus-vector.qza "
        "--o-shannon-vector core-metrics-results/shannon-vector.qza "
        "--o-jaccard-distance-matrix core-metrics-results/jaccard-distance-matrix.qza "
        "--o-jaccard-pcoa-results core-metrics-results/jaccard-pcoa-results.qza "
        "--o-bray-curtis-pcoa-results core-metrics-results/bray-curtis-pcoa-results.qza "
        "--o-jaccard-emperor core-metrics-results/jaccard-emperor.qzv "
        "--o-bray-curtis-emperor core-metrics-results/bray-curtis-emperor.qzv "
        "--o-weighted-unifrac-distance-matrix core-metrics-results/weighted-unifrac-distace-matrix.qza "
        "--o-unweighted-unifrac-pcoa-results core-metrics-results/unweighted-unifrac-pcoa-results.qza "
        "--o-weighted-unifrac-pcoa-results core-metrics-results/weighted-unifrac-pcoa-results.qza "
        "--o-unweighted-unifrac-emperor core-metrics-results/unweighted-unifrac-emperor.qzv "
        "--o-weighted-unifrac-emperor core-metrics-results/weighted-unifrac-emperor.qzv"

rule bray_curtis_plot:
    input:
        "core-metrics-results/bray_curtis_distance_matrix.qza",
        metadata = config["metadata"]
    params:
        column = config["beta-div-column"]
    output:
        "core-metrics-results/bray-curtis-plot.qzv"
    conda:
        "envs/qiime2.yml"
    shell:
        "qiime diversity beta-group-significance "
        "--i-distance-matrix core-metrics-results/bray_curtis_distance_matrix.qza "
        "--m-metadata-file {input.metadata} "
        "--m-metadata-column {params.column} "
        "--o-visualization core-metrics-results/bray-curtis-plot.qzv "
        "--p-method permanova "
        "--p-pairwise"

rule unifrac_plot:
    input:
        "core-metrics-results/unweighted_unifrac_distance_matrix.qza",
        metadata = config["metadata"]
    params:
        column = config["beta-div-column"]
    output:
        "core-metrics-results/unifrac-plot.qzv"
    conda:
        "envs/qiime2.yml"
    shell:
        "qiime diversity beta-group-significance "
        "--i-distance-matrix core-metrics-results/unweighted_unifrac_distance_matrix.qza "
        "--m-metadata-file {input.metadata} "
        "--m-metadata-column {params.column} "
        "--o-visualization core-metrics-results/unifrac-plot.qzv "
        "--p-method permanova "
        "--p-pairwise"

rule evenness_alpha:
    input:
        "core-metrics-results/evenness_vector.qza"
    output:
        "core-metrics-results/evenness-group-significance.qzv"
    conda:
        "envs/qiime2.yml"
    shell:
        "qiime diversity alpha-group-significance "
        "--i-alpha-diversity core-metrics-results/evenness_vector.qza "
        "--m-metadata-file data/paired_end_metadata.tsv "
        "--o-visualization core-metrics-results/evenness-group-significance.qzv"

"""
rule chao1_alpha:
    input:
        "--i-table table-filtered.qza "
    params:
        metric = config["alpha_diversity"]
    output:
        "--o-alpha-diversity core-metrics-results/observed_otus_vector.qza"
    conda:
        "envs/qiime2-2022.2.yml"
    shell:
        "qiime diversity alpha "
        "--i-table table-filtered.qza "
        "--p-metric chao1 "
        "--o-alpha-diversity core-metrics-results/observed_otus_vector.qza"
"""

rule chao1_visual:
    input:
        "core-metrics-results/observed-otus-vector.qza",
        metadata = config['metadata']
    output:
        "core-metrics-results/observed-otus-vector.qzv"
    conda:
        "envs/qiime2.yml"
    shell:
        "qiime diversity alpha-group-significance "
        "--i-alpha-diversity core-metrics-results/observed-otus-vector.qza "
        "--m-metadata-file {input.metadata} "
        "--o-visualization core-metrics-results/observed-otus-vector.qzv"

rule shannon_visual:
    input:
        "core-metrics-results/shannon-vector.qza",
        metadata = config['metadata']
    output:
        "core-metrics-results/shannon-vector.qzv"
    conda:
        "envs/qiime2.yml"
    shell:
        "qiime diversity alpha-group-significance "
        "--i-alpha-diversity core-metrics-results/shannon-vector.qza "
        "--m-metadata-file {input.metadata} "
        "--o-visualization core-metrics-results/shannon-vector.qzv"

rule faith_alpha:
    input:
        "core-metrics-results/faith_pd_vector.qza"
    output:
        "core-metrics-results/faith_pd.qzv"
    conda:
        "envs/qiime2.yml"
    shell:
        "qiime diversity alpha-group-significance "
        "--i-alpha-diversity core-metrics-results/faith_pd_vector.qza "
        "--m-metadata-file data/paired_end_metadata.tsv "
        "--o-visualization core-metrics-results/faith_pd.qzv"

rule taxa_barplot:
    input: 
        "artifacts/demux-paired-end.qzv",
        "artifacts/table-filtered.qzv",
        "artifacts/demux-paired-end-rep-seqs.qzv",
        "artifacts/alpha-rarefaction.qzv",
        table = "artifacts/table-filtered.qza",
        taxonomy = "artifacts/taxonomy.qza",
        metadata = config["metadata"]
    output: 
        "artifacts/taxa-barplot.qzv"
    conda:
        "envs/qiime2.yml"
    shell: 
        "qiime taxa barplot "
        "--i-table {input.table} "
        "--i-taxonomy {input.taxonomy} "
        "--m-metadata-file {input.metadata} "
        "--o-visualization {output}"

rule export_bray_curtis:
    input: 
        "core-metrics-results/bray_curtis_distance_matrix.qza"
    output: 
        "bray-distance-matrix/distance-matrix.tsv"
    conda:
        "envs/qiime2.yml"
    shell: 
        "qiime tools export "
        "--input-path core-metrics-results/bray_curtis_distance_matrix.qza "
        "--output-path bray-distance-matrix"

rule export_unifrac:
    input: 
        "core-metrics-results/unweighted_unifrac_distance_matrix.qza"
    output: 
        "unifrac-distance-matrix/distance-matrix.tsv"
    conda:
        "envs/qiime2.yml"
    shell: 
        "qiime tools export "
        "--input-path core-metrics-results/unweighted_unifrac_distance_matrix.qza "
        "--output-path unifrac-distance-matrix"

rule bray_matrix:
    input:
        "bray-distance-matrix/distance-matrix.tsv"
    output:
        "bray-distance-matrix/nmds-bray.txt"
    conda:
        "envs/qiime2.yml"
    shell:
        "nmds.py bray-distance-matrix/distance-matrix.tsv "
        "-o bray-distance-matrix/nmds-bray.txt "
        "-d 2"

rule unifrac_matrix:
    input:
        "unifrac-distance-matrix/distance-matrix.tsv"
    output:
        "unifrac-distance-matrix/nmds-unifrac.txt"
    conda:
        "envs/qiime2.yml"
    shell:
        "nmds.py unifrac-distance-matrix/distance-matrix.tsv "
        "-o unifrac-distance-matrix/unifrac-bray.txt "
        "-d 2"

rule export_table:
    input: 
        "artifacts/rarefied-table-filtered.qza"
    output: 
        "OTU-table/feature-table.biom"
    conda:
        "envs/qiime2.yml"
    shell: 
        "qiime tools export "
        "--input-path artifacts/table-filtered.qza "
        "--output-path OTU-table"

rule export_taxonomy:
    input:
        "artifacts/taxonomy.qza"
    output:
        "taxonomy/taxonomy.tsv"    
    conda:
        "envs/qiime2.yml"
    shell:
        "qiime tools export "
        "--input-path artifacts/taxonomy.qza "
        "--output-path taxonomy"

rule biom_to_tsv:
    input: 
        "OTU-table/feature-table.biom"
    output: 
        "qiime_output/feature-table.tsv"
    conda:
        "envs/qiime2.yml"
    shell:
        "biom convert "
        "-i OTU-table/feature-table.biom "
        "-o qiime_output/feature-table.tsv "
        "--to-tsv"
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ END OF QIIME2 ANALYSIS SECTION ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ BEGINNING OF R ANALYSIS/VISUALIZATION ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rule qza_to_phyloseq:
    input:
        features = "artifacts/table-filtered.qza",
        tree = "artifacts/rooted-tree.qza",
        taxonomy = "artifacts/taxonomy.qza",
        metadata = config["metadata"]
    threads:
        config['threads']['qza_to_phyloseq']
    output:
        "artifacts/physeq.RDS"
    conda:
        "envs/qiime2r.yaml"
    script:
        "scripts/qza_to_phyloseq.R"

rule r_alpha_div:
    input:
        phyloseq = "artifacts/physeq.RDS"
    output:
        "visual_outputs/alpha_div.pdf"
    params:
        color = config["alpha_color_category"],
        xaxis = config["alpha_x_category"]
    conda:
        "envs/qiime2r.yaml"
    script:
        "scripts/r_alpha_div.R"

rule r_beta_div:
    input:
        phyloseq = "artifacts/physeq.RDS"
    output:
        "visual_outputs/beta_div.pdf"
    params:
        category = config["beta_comparison_category"]
    conda:
        "envs/qiime2r.yaml"
    script:
        "scripts/r_beta_div.R"

rule r_relative_barplot:
    input:
        phyloseq = "artifacts/physeq.RDS"
    output:
        "visual_outputs/relative_barplot.pdf"
    params:
        taxalevel = config["taxa_lower_level_barplot"],
        taxacomparison = config["taxa_comparison_category"]
    conda:
        "envs/qiime2r.yaml"
    script:
        "scripts/r_relative_barplot.R"

rule r_absolute_barplot:
    input:
        phyloseq = "artifacts/physeq.RDS"
    output:
        "visual_outputs/absolute_barplot.pdf"
    params:
        taxalevel = config["taxa_lower_level_barplot"],
        taxacomparison = config["taxa_comparison_category"]
    conda:
        "envs/qiime2r.yaml"
    script:
        "scripts/r_absolute_barplot.R"

rule r_heatmap:
    input:
        phyloseq = "artifacts/physeq.RDS"
    output:
        "visual_outputs/heatmap.pdf"
    params:
        taxalevel = config["heatmap_level"],
        taxacomparison = config["heatmap_comparison_category"],
        samplingdepth = config["sampling_depth_phylogenetic"]
    conda:
        "envs/qiime2r.yaml"
    script:
        "scripts/r_heatmap.R"
