# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 
rule testrule:
  log:
    "logs/test.log"
  conda:
    "envs/test_env.yaml"
  shell:
    'echo "Hello World!"'
#this is a workflow that's so cool