# QIIME2
manifest: 
  "data/metadata/aim1_manifest.tsv"
metadata:
  "data/metadata/aim1_metadata.tsv"

data_format: # format of reads to be imported; note the double quotations for string form
  #"'CasavaOneEightSingleLanePerSampleDirFmt'"
  "'PairedEndFastqManifestPhred33V2'"
  #"'PairedEndFastqManifestPhred64V2'"

classifier:
  "classifier/silva-138-99-nb-classifier.qza"
  #"classifier/longitudinal_classifier.qza"

table-frequency: #minimum frequency a feature must show or it will be filtered out
  "10"

table-include: #only include features classified down to the selected taxonomic level
  "p__"
  #"c__"
  #"k__"

table-filter: #determines which features will be removed from table due to host genome, etc.
  "chloroplast,mitochondria,eukaryota" 
#must be comma separated with no spaces for each group you'd like to filter

beta-div-column: #which variable from metadata file is being measured
  "Groups"

# manual trimming; note that the parameters are string form
trunclenf:
  "237"
trunclenr:
  "213"
trimleftf:
  "40"
trimleftr:
  "40"

sampling_depth_phylogenetic:
  "5000"

threads:
  denoising: 16
  classify_sklearn: 16
  qza_to_phyloseq: 8

alpha_color_category:
  "Group"

alpha_x_category:
  "Chrono_TP"

beta_comparison_category:
  "Group"

taxa_lower_level_barplot:
  "Genus"

taxa_comparison_category:
  "Group"

heatmap_level:
  "Order"

heatmap_comparison_category:
  "Group"

# QIIME2 pipeline outputs
# set these files as your targets at the top of your Snakefile

#  STEP 1 this is for choosing filter parameters
#  "artifacts/demux-paired-end.qzv"

#  STEP 2 this is for choosing sampling depth
#  "artifacts/table-viz.qzv", "artifacts/rooted-tree.qza"

#  STEP 3 choose a prebuilt visual output
#  "visual_outputs/alpha_div.pdf", "visual_outputs/beta_div.pdf", "visual_outputs/absolute_barplot.pdf", "visual_outputs/heatmap.pdf"

#  NOTE- if you wish to skip the prebuilt visual options and instead jump right into custom output, set this as your target for STEP 3 of the pipeline:
#   "artifacts/physeq.RDS"
