# QIIME2
manifest: 
  "data/paired_end_manifest.tsv"
metadata:
  "data/paired_end_metadata.tsv"

tools:
  #"DADA2"
  Qiime2:
    #- "artifacts/taxonomy.qza"
    - "artifacts/unweighted-unifrac-pcoa-matrix.qza"
  #Mothur:
  #Pathoscope2:
  #Kraken:

classifier:
  classifier/silva-138-99-nb-classifier.qza

table-filter:
  "chloroplast,mitochondria,eukaryota,unassigned"

beta-div-column:
  "Groups"

trunclenf:
  "270"
trunclenr:
  "230"
trimleftf:
  "10"
trimleftr:
  "15"

sampling_depth:
  "1103"
sampling_depth_phylogenetic:
  "146159"