manifest: 
  "data/paired_end_manifest.tsv"

# tools
"DADA2": false,
"Qiime2": true,
"Mothur": false,
"Pathoscope2": false,
"Kraken": false,

classifier:
  "Greengenes"
  "Silva"
  "Kraken2"
  "RefSeq"

trunc-len-f:
  "270"
trunc-len-r:
  "230"
trim-left-f:
  "10"
trim-left-r:
  "10"